config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users
  resources :organizations
  resources :boards do
    resources :messages, only: %i[create update new edit]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :created_by, class_name: 'User'
  has_many :messages

  validates :name, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :board
  belongs_to :author, class_name: "User"

  validates :content, presence: true
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :users
  has_many :boards, through: :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :organization
  has_many :boards, foreign_key: :created_by_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:organization_id])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:organization_id])
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def new
    @board = current_user.boards.new()
  end

  def index
    @boards = current_user.boards.all
    @boards
  end

  def create
    @board = current_user.boards.create(board_params)
    if @board.save
      flash.now[:notice] = "Your board was created!"
      redirect_to boards_path
    else
      flash.now[:alert] = "Your board was not created!"
      render 'new'
    end
  end

  def show
    @board = current_user.boards&.find(params[:id])
    @messages = @board&.messages
  end

  def edit
    @board = current_user.boards&.find(params[:id])
  end

  def update
    @board = current_user.boards&.find(params[:id])
    @boards = current_user.boards.all

    if @board.update(board_params)
      redirect_to boards_path
    else
      render 'edit'
    end
  end

  def destroy
    @board = current_user.boards.find(params[:id])
    @board.destroy

    if @board.destroy
      respond_to do |format|
        format.html { redirect_to boards_path }
        format.xml  { head :ok }
      end
    end
  end

  private

  def board_params
    params.require(:board).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_board
  def new
    @message = @board.messages.build
  end

  def create
    @message = @board.messages.new(message_params)
    @message.author = current_user
    if @message.save
       respond_to do |format|
        format.html { redirect_to(@board) }
       end
    else
      render :new
    end
  end

  def edit
    @message = @board.messages.find(params[:id])
  end

  def update
    @message = @board.messages.find(params[:id])

    if @message.update(message_params)
      redirect_to @board
    else
      render 'edit'
    end
  end

  private

  def set_board
    @board = current_user.organization.boards.find(params[:board_id])
  end

  def message_params
    params.require(:message).permit(:content, :category)
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def index
    @organizations = Organization.all
    @organizations
  end

  def create
    @organization = Organization.new(params[:created_by, ])
    if @organization.save
      @organization
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shared_helper.rb
module SharedHelper
  def user_name(name)
    split_email = name.split('@')
    split_email[0]
  end
end

app/views/boards/edit.html.erb
<%= turbo_frame_tag dom_id(@board) do %>
  <%= form_with model: @board, url: [@board] do |f| %>
    <div class="field">
      <%= f.text_field :name, placeholder: 'new name' %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
<% end %>

<%# end %>

app/views/boards/index.html.erb
<div>
  <h1>Board List</h1>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">NAME</th>
      <th scope="col">GO</th>
      <th scope="col">DELETE</th>
    </tr>
  </thead>
  <tbody>
    <% @boards.map do |board| %>
      <tr>
        <td><%= board.id %></td>
        <td><%= board.name %></td>
        <td><%= link_to 'GO', board_path(board.id), class: 'cta-link' %></td>
        <td><%= button_to 'DELETE', board_path(board), method: 'delete', class: 'cta-link' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="mt-5">
  <%= link_to 'Create Board', new_board_path, class: "cta-btn" %>
</div>

app/views/boards/new.html.erb
<div class="wrap-new-board">
  <h1 class="text-center">CREATE A NEW BOARD 🙌🏽</h1>
  <div class="form-new-board">
    <%= form_with model: Board.new do |f|%>
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, class: 'w-100 input-gray' %>
      </div>

      <div class="actions mt-4">
        <%= f.submit "Create Board", class: "cta-btn w-100" %>
      </div>
    <% end %>

    <%= link_to 'View Board List', boards_path, class: "cta-link w-100 mt-2 text-center" %>
  </div>
</div>

app/views/boards/show.html.erb
<h3 class="text-center board-name"><%= @board.name %></h3>
<div class="board-wrap">
  <div class="card card-category position-relative">
    <h4>Went Well</h4>
    <% @messages&.select { |m| m.category == 'good' }.each do |m| %>
        <div class="message">
          <% frame_id = dom_id(m, "content_turbo_frame") %>
          <%= form_with model: m, url: [@board, @message], class: 'message-content', data: { turbo_frame: frame_id } do |form| %>
            <%= turbo_frame_tag frame_id do %>
              <p class="mt-4 mb-0"><%= m.content %></p>
              <%= link_to 'edit', edit_board_message_path(m.board_id, m.id), class: 'message-edit', data: { turbo_frame: frame_id } %>
            <% end %>
          <% end %>
        </div>
    <% end %>
    <%= link_to 'Add comment', new_board_message_path(@board.id), class: 'cta-link position-absolute bottom-15' %>
  </div>
  <div class="card card-category position-relative">
    <h4>To Improve</h4>
    <% @messages&.select { |m| m.category == 'improve' }.each do |m| %>
      <div class="message">
        <% frame_id = dom_id(m, "content_turbo_frame") %>
        <%= form_with model: m, url: [@board, @message], class: 'message-content', data: { turbo_frame: frame_id } do |form| %>
          <%= turbo_frame_tag frame_id do %>
            <p class="mt-4 mb-0"><%= m.content %></p>
            <%= link_to 'edit', edit_board_message_path(m.board_id, m.id) %>
          <% end %>
        <% end %>
      </div>
    <% end %>
    <%= link_to 'Add comment', new_board_message_path(@board.id), class: 'cta-link position-absolute bottom-15' %>
  </div>
  <div class="card card-category position-relative">
    <h4>Action Items</h4>
    <% @messages&.select { |m| m.category == 'actions' }.each do |m| %>
      <div class="message">
        <% frame_id = dom_id(m, "content_turbo_frame") %>
        <%= form_with model: m, url: [@board, @message], class: 'message-content', data: { turbo_frame: frame_id } do |form| %>
          <%= turbo_frame_tag frame_id do %>
            <p class="mt-4 mb-0"><%= m.content %></p>
            <%= link_to 'edit', edit_board_message_path(m.board_id, m.id) %>
          <% end %>
        <% end %>
      </div>
    <% end %>
    <%= link_to 'Add comment', new_board_message_path(@board.id), class: 'cta-link position-absolute bottom-15' %>
  </div>
</div>

<%= link_to 'View Board List', boards_path, class: 'cta-link' %>

app/views/home/index.html.erb
<div class="welcome">
  <% if current_user %>
    <div class="title">
      <h1>Welcome @</h1>
      <h1><%= user_name(current_user.email) %></h1>
    </div>
    <div class="wrap-btn">
    <%= link_to 'Create Board', new_board_path, class: "cta-btn" %>
    <%= link_to 'Board list', boards_path, class: "cta-link" %>
    </div>
  <%end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Retroboard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body class="container">
    <%= render 'shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<% frame_id = dom_id(@message, "content_turbo_frame") %>
<%= turbo_frame_tag frame_id, class: 'contents' do %>
  <%= form_with model: @message, url: [@board, @message] do |f| %>
    <%= f.text_area :content, placeholder: 'new message', class: 'input-gray w-300 text-area-fixed mt-4' %>
    <div class="actions">
      <%= f.submit 'Update', class: "cta-btn w-300" %>
    </div>
  <% end %>
<% end %>

app/views/messages/edit.html.erb
<div class="container" style="margin: 30px">
<!--  <p><%#= @message.errors.full_messages.to_sentence %></p>-->
  <%= render 'form', locals: { message: @message, board: @board } %>
</div>

app/views/messages/new.html.erb
<div class="mt-4">
  <%= turbo_frame_tag "new_message", target: "_top" do %>
    <p class="fw-bold">New Message</p>
    <%= form_with model: [@board, @message] do |f| %>
      <div class="field">
        <%= f.text_area :content, placeholder: 'new message', class: 'input-gray w-300 text-area-fixed' %>
      </div>

      <div class="field position-relative mb-3">
        <div class="select-arrow"></div>
        <%= f.select :category, [['Good', 'good'], ['Improve', 'improve'], ['Actions', 'actions']], {}, include_blank: false, class: 'select-gray' %>
      </div>
      <div class="actions">
        <%= f.submit 'Add Message', class: "cta-btn w-300" %>
      </div>
      <%= link_to 'Back to Board', board_path(@board.id), class: 'cta-link' %>
    <% end %>
  <% end %>
</div>

app/views/organizations/index.html.erb
<div>
  <h1>Organizations</h1>
  <% @organizations.map do |org| %>
    <table style="display: flex">
      <tr>
        <th>Id</th>
        <th>Name</th>
      </tr>
      <tr>
        <td><%= org.id %></td>
        <td><%= org.name %></td>
      </tr>
    </table>
<% end %>
</div>

app/views/shared/_nav.html.erb
<div class="navbar">
  <div>
    <%= link_to image_tag('retroicon.png', width: '80'), root_path %>
  </div>
  <div class="d-flex">
    <% if current_user %>
      <%= button_to 'Sign out', destroy_user_session_path, method: :delete, form_class: "cta-btn-devise-out mr-15" %>
      <%= link_to 'Profile', root_path, class: "cta-btn-devise" %>
  <% else %>
      <%= link_to 'Sign up', new_user_registration_path, class: "cta-btn-devise mr-15" %>
      <%= link_to 'Sign in', new_user_session_path, class: "cta-btn-devise" %>
    <% end %>
  </div>
</div>